### ISSUE TITLE
Internationalisation failing on the top menu

### ISSUE THREAD

**Issue by iglocska** [monarc-project/ng-client#4]
Setting the language to English keeps the hover bubbles when hovering over the analysis phases stuck in French.

**Comment by cedricbonhomme** [comment]
You mean the bubbles in the breadcrumb with the analysis steps?
Indeed, the Web page has to be reloaded after a language changes. I'll look at this.

But the language of the bubbles in the information risks table cannot be changed. The data you can read here are part of the analysis (and can be updated via the knowledge base). These data can be entered by hand or you can use the data we provide by default.
When you create a new analysis you have to select a language, and then it is fixed. You will still be able to change the language of MONARC (I mean the Web interface) but not the data like the risks, threats, etc. added by the user.

**Comment by cedricbonhomme** [comment]
fixed [here](https://github.com/monarc-project/ng-client/pull/21)
